version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  front-end:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
